"""
Data Pipeline Module for the Smart Alloy Selector.
Executes data ingestion, deterministic missing value imputation, ordinal mapping,
and derivation of physics-based materials features (Ashby indices).
"""

import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

class MaterialsDataPipeline:
    def __init__(self, filepath: str):
        """
        Initializes the data pipeline with the target dataset filepath.
        Establishes the ordinal scaling dictionary for qualitative materials traits.
        """
        self.filepath = filepath
        self.raw_data = None
        self.processed_data = None
        
        # Establishing a numerical taxonomy for qualitative descriptors
        # This allows MCDM algorithms to evaluate abstract traits mathematically
        self.ordinal_mapping = {
            'Excellent': 5.0,
            'Very Good': 4.0,
            'Good': 3.0,
            'Fair': 2.0,
            'Poor': 1.0,
            'Very Poor': 0.0,
            'N/A': np.nan
        }

    def load_data(self) -> pd.DataFrame:
        """Ingests the raw materials database from the local file system."""
        self.raw_data = pd.read_csv(self.filepath)
        return self.raw_data

    def _encode_ordinal_features(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Transforms qualitative assessments into continuous numerical variables.
        Critical for enabling geometric distance calculations in TOPSIS.
        """
        categorical_cols = ['corrosion_resistance', 'machinability', 'weldability']
        for col in categorical_cols:
            if col in df.columns:
                df[col] = df[col].replace(self.ordinal_mapping)
                df[col] = pd.to_numeric(df[col], errors='coerce')
        return df

    def _handle_missing_values(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Implements strategic imputation to handle sparse empirical data.
        Utilizes median imputation for numeric attributes to mitigate outlier bias,
        and mode imputation for remaining unmapped categorical strings.
        """
        numeric_cols = df.select_dtypes(include=[np.number]).columns
        categorical_cols = df.select_dtypes(exclude=[np.number]).columns

        if len(numeric_cols) > 0:
            num_imputer = SimpleImputer(strategy='median')
            df[numeric_cols] = num_imputer.fit_transform(df[numeric_cols])

        if len(categorical_cols) > 0:
            cat_imputer = SimpleImputer(strategy='most_frequent')
            df[categorical_cols] = cat_imputer.fit_transform(df[categorical_cols])

        return df

    def _engineer_features(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Generates Ashby performance indices. These derived parameters are 
        fundamental in structural design optimization, representing the efficiency 
        of a material relative to its mass.
        """
        if 'yield_strength_mpa' in df.columns and 'density_g_cm3' in df.columns:
            # Identifies materials that maximize strength while minimizing weight
            df['specific_strength'] = df['yield_strength_mpa'] / df['density_g_cm3']
            
        if 'elastic_modulus_gpa' in df.columns and 'density_g_cm3' in df.columns:
            # Identifies materials that maximize stiffness while minimizing weight
            df['specific_stiffness'] = df['elastic_modulus_gpa'] / df['density_g_cm3']
            
        return df

    def process_pipeline(self) -> pd.DataFrame:
        """
        Orchestrates the sequential execution of all data sanitization, 
        imputation, and feature engineering procedures.
        """
        if self.raw_data is None:
            self.load_data()
            
        df = self.raw_data.copy()
        
        # Eradicate explicit string nulls generated by manual data entry
        df.replace("N/A", np.nan, inplace=True)
        
        # Execute processing subroutines
        df = self._encode_ordinal_features(df)
        
        # Enforce strict numeric types on critical engineering features
        numeric_targets = [
            'yield_strength_mpa', 'tensile_strength_mpa', 'elastic_modulus_gpa', 
            'melting_point_c', 'max_service_temp_c', 'thermal_conductivity_w_mk', 
            'cost_usd_kg', 'hardness_hv', 'fatigue_strength_mpa'
        ]
        for col in numeric_targets:
            if col in df.columns:
                df[col] = pd.to_numeric(df[col], errors='coerce')
                
        df = self._handle_missing_values(df)
        df = self._engineer_features(df)
        
        self.processed_data = df
        return self.processed_data